library(shiny)
library(shinythemes)
library(dplyr)
library(DT)
library(shinyWidgets)
library(shinycssloaders)
library(shinyjs)
library(markdown)

times <- strftime(seq(ISOdate(2000, 1, 1, hour = 8), by = "min", length.out = 541), format = "%I:%M:%S %p")
